### ISSUE TITLE
can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by Hellsender01** [tigertv/secretpy#4]
plaintext = u"string"

**Works fine**

# Problem
What if we have to ask plaintext from user, how can we **unicode** it now.
Python 3.x does not support unicode() function

**My Code**
```py

cipher = secretpy.Vigenere()

string = input("Enter Plaintext")
key = input("Enter Key")

def encrypt_vigenere(string,key):
    encrypted_string = cipher.encrypt(string,key)
    return encrypted_string

encrypt_vigenere(string,key)
```
# Error
```py
File "/usr/local/lib/python3.8/dist-packages/secretpy/ciphers/vigenere.py", line 43, in encrypt
    return self.__encDec(alphabet, key, text, 1)
File "/usr/local/lib/python3.8/dist-packages/secretpy/ciphers/vigenere.py", line 19, in __encDec
    raise Exception("Can't find char '" + wrchar + "' of text in alphabet!")
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by tigertv** [comment]
Hi, @Hellsender01 !
Would you say what you input and what alphabet you use?

**Comment by Hellsender01** [comment]
Why do you use `encrypt_vigenere()` and not `cipher.encrypt()`?

Actually the whole program is big, i have just provided u the buggy part
**i just saw that `space` is causing this error**

**works fine**

input = "hello"

**this is what causing the problem**

input = "hello world"

**Comment by tigertv** [comment]
This happens because ' '(space) doesn't exist in the alphabet. 
You can add space in your alphabet or you can use the wrappers 'SaveAll' and 'RemoveNonAlphabet' which save and remove non-alphabet characters correspondingly
https://github.com/tigertv/secretpy/blob/b87b822cbd9776660e51c4cf7ccbaaeec97faab0/examples/caesar.py#L42-L48

_Originally posted by @tigertv in https://github.com/tigertv/secretpy/issues/3#issuecomment-735432534_

**Comment by Hellsender01** [comment]
Ok Thanks...
